### PR TITLE
fix(deps): remove alpha dependencies

### PR DESCRIPTION
**Pull request by daniel-heppner-ibigroup**
Remove dependencies on the alpha branch.

### CODE REVIEW

**Review by binh-dam-ibigroup — CHANGES_REQUESTED** [review]
Could you fix the TypeScript errors, please @daniel-heppner-ibigroup?

**Comment by daniel-heppner-ibigroup** [comment]
What the heck, where did these completely unrelated typescript errors come from? 😠 I'll take a look

**Comment by daniel-heppner-ibigroup** [comment]
@binh-dam-ibigroup Looks like this was a bug from another PR to types which was only caught here by upgrading the package version in core utils.

**Review by binh-dam-ibigroup — APPROVED** [review]

**Review by miles-grant-ibigroup — APPROVED** [review]
Great fixes thanks!

**Pull request merged**
