### PR TITLE
revert(TripDetails): Revert previous commit

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**

### CODE REVIEW

**Comment by landonreed** [comment]
@binh-dam-ibigroup, does this PR need to exist?

**Comment by binh-dam-ibigroup** [comment]
> @binh-dam-ibigroup, does this PR need to exist?

Only if we still need the `alpha` branch, otherwise I can close it.

**Comment by binh-dam-ibigroup** [comment]
@landonreed this PR will be moot once https://github.com/opentripplanner/otp-ui/pull/177 is merged.

**Comment by landonreed** [comment]
In that case, let's just close this.

**Pull request closed without merging**
