### PR TITLE
fix: add property to TransitVehicle

### PR DESCRIPTION
**Pull request by mcleinman**
Adding routeColor to the vehicle object.

This will help TriMet's usage of OTP-UI by allowing us to remove a hacky file that replicates routeColor for vehicle objects, and instead use the server-provided color everywhere.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
This change looks good to me, however how are you planning on using this type change? Is there a specific package that will need updating?

**Comment by binh-dam-ibigroup** [comment]
I recommend having changes from #436 merged first so that type checks can pass.

**Comment by miles-grant-ibigroup** [comment]
Merging `master` into this branch should resolve all failing tests!

**Review by binh-dam-ibigroup — APPROVED** [review]

**Comment by binh-dam-ibigroup** [comment]
Hi @mcleinman, regarding the CI errors, try merging branch `master` into your PR and that should take care of the type errors.

**Comment by mcleinman** [comment]
Apologies on the delay on this one - I'm going to close this, and later re-open one based on the `raster-tiles` branch. Thanks!

**Comment by mcleinman** [comment]
In case anyone is curious, https://github.com/opentripplanner/otp-ui/pull/442 actually provides the same functionality as this one does - so this won't be re-opened.

**Pull request closed without merging**
