### PR TITLE
update internal dependency versions

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Some package updates aren't working in otp-rr due to missing internal dependency updates. This PR resolves that.

### CODE REVIEW

**Review by daniel-heppner-ibigroup — CHANGES_REQUESTED** [review]
This is causing yarn.lock to update for me when I run yarn. I deleted node_modules and started over but still got a change to yarn.lock.

**Comment by miles-grant-ibigroup** [comment]
Have committed a new lock file, let me know if it works for you

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Thank you!

**Review by philip-cline — APPROVED** [review]
Looking good to me too

**Pull request merged**
